### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by impredicative** [yaserkl/TransferRL#3]
Please think about whether it makes sense to share some pretrained models. They can often be useful.

**Comment by yaserkl** [comment]
Yeah, we are planning to share our pre-trained best performing model this week on Google Drive. Stay tuned for it.

**Comment by yaserkl** [comment]
I updated the repo with a link to our best-performing model.

**Comment by impredicative** [comment]
Great. I can maybe figure this out in my own, but where should I look for sample code for using the model with my data? I mean for (1) continuing training (transfer learning) (2) using directly for predictions only.

Or if you have no further comments, feel free to close this issue.

**Comment by yaserkl** [comment]
I've mentioned it in the Readme, I've put all the commands required for training/evaluating/decoding in this file: src/helper/commands.txt
